spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
        connection-timeout: 30000
        initialization-fail-timeout: 0
        maximum-pool-size: 5
        pool-name: EwmHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      connection.provider_disables_autocommit: true
      logging:
        level:
          org.springframework.web: DEBUG
          org.springframework.http.converter.json: TRACE
          com.fasterxml.jackson.databind: TRACE

stats-server:
  url: http://stats-server:9090

