spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: TRACE

  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

stats:
  server:
    url: http://stats-server:9090

server:
  port: 8080
