spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

stats-server:
  url: http://stats-server:9090