CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255)             NOT NULL,
    name       VARCHAR(512)             NOT NULL
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        annotation VARCHAR(2000) NOT NULL,
                        description VARCHAR(7000),
                        event_date TIMESTAMP NOT NULL,
                        lat FLOAT,
                        lon FLOAT,
                        paid BOOLEAN DEFAULT FALSE,
                        participant_limit INT DEFAULT 0,
                        request_moderation BOOLEAN DEFAULT TRUE,
                        title VARCHAR(120) NOT NULL,
                        category_id BIGINT NOT NULL,
                        user_id BIGINT NOT NULL,
                        state VARCHAR(20) DEFAULT 'PENDING',
                        created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        published_on TIMESTAMP,
                        FOREIGN KEY (category_id) REFERENCES categories(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE participation_requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        event_id BIGINT NOT NULL REFERENCES events(id),
                                        requester_id BIGINT NOT NULL REFERENCES users(id),
                                        status VARCHAR(20) NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        UNIQUE (event_id, requester_id)
);
CREATE TABLE compilations (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pinned BOOLEAN NOT NULL DEFAULT false,
                              title VARCHAR(50) NOT NULL
);

CREATE TABLE compilation_events (
                                    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
                                    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
                                    PRIMARY KEY (compilation_id, event_id)
);
