CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255)             NOT NULL,
    name       VARCHAR(512)             NOT NULL
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        annotation VARCHAR(2000) NOT NULL,
                        description VARCHAR(7000),
                        event_date TIMESTAMP NOT NULL,
                        lat FLOAT,
                        lon FLOAT,
                        paid BOOLEAN DEFAULT FALSE,
                        participant_limit INT DEFAULT 0,
                        request_moderation BOOLEAN DEFAULT TRUE,
                        title VARCHAR(120) NOT NULL,
                        category_id BIGINT NOT NULL,
                        user_id BIGINT NOT NULL,
                        FOREIGN KEY (category_id) REFERENCES categories(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
);
