services:
  stats-server:
    image: stats-server
    build: ./stats/server
    ports:
      - "9090:9090"
    environment:
          WAIT_HOSTS: stats-server:9090
          WAIT_HOSTS_TIMEOUT: 120

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
    ports:
      - "5432:5432"




  ewm-service:
    image: ewm-service
    build: ./main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1

  stats-client:
    image: stats-client
    build: ./stats/stats-client
    ports:
      - "9091:9091"
    depends_on:
      - stats-server