spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      connection.provider_disables_autocommit: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
server:
  port: 9090