spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Или validate, если таблицы созданы вручную
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
server:
  port: 9090