spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    ru.practicum: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 9090